// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Diagnose is the predicate function for diagnose builders.
type Diagnose func(*sql.Selector)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)
