// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/ADMIN/app/ent/department"
	"github.com/ADMIN/app/ent/disease"
	"github.com/ADMIN/app/ent/doctor"
	"github.com/ADMIN/app/ent/patient"
	"github.com/ADMIN/app/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescDepartmentName is the schema descriptor for Department_Name field.
	departmentDescDepartmentName := departmentFields[0].Descriptor()
	// department.DepartmentNameValidator is a validator for the "Department_Name" field. It is called by the builders before save.
	department.DepartmentNameValidator = departmentDescDepartmentName.Validators[0].(func(string) error)
	diseaseFields := schema.Disease{}.Fields()
	_ = diseaseFields
	// diseaseDescDiseaseName is the schema descriptor for Disease_Name field.
	diseaseDescDiseaseName := diseaseFields[0].Descriptor()
	// disease.DiseaseNameValidator is a validator for the "Disease_Name" field. It is called by the builders before save.
	disease.DiseaseNameValidator = diseaseDescDiseaseName.Validators[0].(func(string) error)
	doctorFields := schema.Doctor{}.Fields()
	_ = doctorFields
	// doctorDescDoctorName is the schema descriptor for Doctor_Name field.
	doctorDescDoctorName := doctorFields[0].Descriptor()
	// doctor.DoctorNameValidator is a validator for the "Doctor_Name" field. It is called by the builders before save.
	doctor.DoctorNameValidator = doctorDescDoctorName.Validators[0].(func(string) error)
	// doctorDescDoctorPassword is the schema descriptor for Doctor_Password field.
	doctorDescDoctorPassword := doctorFields[1].Descriptor()
	// doctor.DoctorPasswordValidator is a validator for the "Doctor_Password" field. It is called by the builders before save.
	doctor.DoctorPasswordValidator = doctorDescDoctorPassword.Validators[0].(func(string) error)
	// doctorDescDoctorEmail is the schema descriptor for Doctor_Email field.
	doctorDescDoctorEmail := doctorFields[2].Descriptor()
	// doctor.DoctorEmailValidator is a validator for the "Doctor_Email" field. It is called by the builders before save.
	doctor.DoctorEmailValidator = doctorDescDoctorEmail.Validators[0].(func(string) error)
	// doctorDescDoctorTel is the schema descriptor for Doctor_tel field.
	doctorDescDoctorTel := doctorFields[3].Descriptor()
	// doctor.DoctorTelValidator is a validator for the "Doctor_tel" field. It is called by the builders before save.
	doctor.DoctorTelValidator = doctorDescDoctorTel.Validators[0].(func(string) error)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescPatientName is the schema descriptor for Patient_Name field.
	patientDescPatientName := patientFields[0].Descriptor()
	// patient.PatientNameValidator is a validator for the "Patient_Name" field. It is called by the builders before save.
	patient.PatientNameValidator = patientDescPatientName.Validators[0].(func(string) error)
	// patientDescPatientAge is the schema descriptor for Patient_Age field.
	patientDescPatientAge := patientFields[1].Descriptor()
	// patient.PatientAgeValidator is a validator for the "Patient_Age" field. It is called by the builders before save.
	patient.PatientAgeValidator = patientDescPatientAge.Validators[0].(func(string) error)
	// patientDescPatientWeight is the schema descriptor for Patient_Weight field.
	patientDescPatientWeight := patientFields[2].Descriptor()
	// patient.PatientWeightValidator is a validator for the "Patient_Weight" field. It is called by the builders before save.
	patient.PatientWeightValidator = patientDescPatientWeight.Validators[0].(func(string) error)
	// patientDescPatientHeight is the schema descriptor for Patient_Height field.
	patientDescPatientHeight := patientFields[3].Descriptor()
	// patient.PatientHeightValidator is a validator for the "Patient_Height" field. It is called by the builders before save.
	patient.PatientHeightValidator = patientDescPatientHeight.Validators[0].(func(string) error)
	// patientDescPatientPrefix is the schema descriptor for Patient_Prefix field.
	patientDescPatientPrefix := patientFields[4].Descriptor()
	// patient.PatientPrefixValidator is a validator for the "Patient_Prefix" field. It is called by the builders before save.
	patient.PatientPrefixValidator = patientDescPatientPrefix.Validators[0].(func(string) error)
	// patientDescPatientGender is the schema descriptor for Patient_Gender field.
	patientDescPatientGender := patientFields[5].Descriptor()
	// patient.PatientGenderValidator is a validator for the "Patient_Gender" field. It is called by the builders before save.
	patient.PatientGenderValidator = patientDescPatientGender.Validators[0].(func(string) error)
	// patientDescPatientBlood is the schema descriptor for Patient_Blood field.
	patientDescPatientBlood := patientFields[6].Descriptor()
	// patient.PatientBloodValidator is a validator for the "Patient_Blood" field. It is called by the builders before save.
	patient.PatientBloodValidator = patientDescPatientBlood.Validators[0].(func(string) error)
}
